# Generated by Django 2.2.15 on 2020-09-05 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apirules', '0002_produtos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Insignas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50, null=True)),
                ('descricao', models.CharField(max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Myinsignas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insigna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apirules.Insignas')),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apirules.Perfil')),
            ],
        ),
    ]
