# Generated by Django 2.2.15 on 2020-09-05 22:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apirules', '0003_insignas_myinsignas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.CharField(max_length=100, null=True)),
                ('titulo', models.CharField(max_length=20, null=True)),
                ('descricao', models.TextField(max_length=250, null=True)),
                ('preco', models.FloatField(null=True)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apirules.Perfil')),
            ],
        ),
    ]
